#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Ferdinando M. Ametrano
name: Ferdinando M. Ametrano

# Short bio or description (displayed in the header)
description: Bitcoin and Blockchain Technology

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/3296421?s=460&v=4

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: ferdinando.ametrano
  flickr:
  github: fametrano
  instagram:
  linkedin: ferdinandoametrano/
  pinterest:
  rss: anything # just type anything here for a working RSS icon
  twitter: Ferdinando1970
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: FerdinandoMAmetrano # channel/<your_long_string> or user/<user-name>
  googleplus: # +FerdinandoMAmetrano
  googleform: /d/e/1FAIpQLSc9KffxBFNirQcEBmO1Ept7OSKDOHqV_zEEh0RMIcUEwlu8Xw/viewform # the part after https://docs.google.com/forms/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-126683188-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for sitemap.xml and RSS feed.xml
url: http://www.ametrano.net

# If you're hosting your site at a Project repository on GitHub pages
# (yourusername.github.io/repository-name)
# and NOT your User repository (yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:year/:month/:day/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :expanded

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

include: [_pages]

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
